export const UPDATE_BOOK_APPROVAL_REQUEST = 'UPDATE_BOOK_APPROVAL_REQUEST';
export const UPDATE_BOOK_APPROVAL_SUCCESS = 'UPDATE_BOOK_APPROVAL_SUCCESS';
export const UPDATE_BOOK_APPROVAL_FAILURE = 'UPDATE_BOOK_APPROVAL_FAILURE';

